### ISSUE TITLE
Doesn't import when using Typescript's module:ES2022

### ISSUE THREAD

**Issue by hitsthings** [ChocolateLoverRaj/stream-replace-string#9]
Reproduction is at https://github.com/hitsthings/test-stream-replace-string

The repo also imports dotenv, just as a control variable - dotenv is imported without a problem.

The "fix" in that repo wouldn't work with CJS though, so not opening it as a PR.

**Comment by slyk** [comment]
got same problem

**Comment by ChocolateLoverRaj** [comment]
@hitsthings @slyk How do you want me to fix the problem? Should I remove CJS support? Should I generate a CJS file automatically and publish it along with the esmodule file?

**Comment by hitsthings** [comment]
One option is the custom typing in my reproduction repo which uses export default instead of export =. I don't know how that affects cjs though.

Another is to move `replace` to a named export. Default exports have problems like this that just don't exist with named exports.
If you keep the default export and re-export as a named export as well, that shouldn't be a breaking change.

Maybe there are better ways too! I don't have a lot of experience with publishing libraries.

**Comment by ChocolateLoverRaj** [comment]
@hitsthings I will replace `export = replace` with `export default replace`

**Comment by ChocolateLoverRaj** [comment]
I publisehd v2.0.0. If it's working for you guys then I will close this issue.

**Comment by ChocolateLoverRaj** [comment]
I'm going to assume it's working.
